from template.load_template import load_template

BOND_ICON = load_template("./template/bond/assets/BOND_ICON.png")
CHARA_1 = load_template("./template/bond/assets/CHARA_1.png")
CHARA_2 = load_template("./template/bond/assets/CHARA_2.png")
CHARA_3 = load_template("./template/bond/assets/CHARA_3.png")
CHARA_4 = load_template("./template/bond/assets/CHARA_4.png")
CHARA_5 = load_template("./template/bond/assets/CHARA_5.png")
DATE = load_template("./template/bond/assets/DATE.png")
DATE_TELEPHONE = load_template("./template/bond/assets/DATE_TELEPHONE.png", rect=(1160, 175, 1210, 650))
GIFT = load_template("./template/bond/assets/GIFT.png")
GIFT_1 = load_template("./template/bond/assets/GIFT_1.png")
GIFT_10 = load_template("./template/bond/assets/GIFT_10.png")
GIFT_2 = load_template("./template/bond/assets/GIFT_2.png")
GIFT_3 = load_template("./template/bond/assets/GIFT_3.png")
GIFT_4 = load_template("./template/bond/assets/GIFT_4.png")
GIFT_5 = load_template("./template/bond/assets/GIFT_5.png")
GIFT_6 = load_template("./template/bond/assets/GIFT_6.png")
GIFT_7 = load_template("./template/bond/assets/GIFT_7.png")
GIFT_8 = load_template("./template/bond/assets/GIFT_8.png")
GIFT_9 = load_template("./template/bond/assets/GIFT_9.png")
INVITE_CONFIRM = load_template("./template/bond/assets/INVITE_CONFIRM.png")
LOCKED = load_template("./template/bond/assets/LOCKED.png")
MOVIE_CHAT = load_template("./template/bond/assets/MOVIE_CHAT.png")
NAME = load_template("./template/bond/assets/NAME.png")
PRESENT = load_template("./template/bond/assets/PRESENT.png")