from template.load_template import load_template

BOND = load_template("./template/ui/assets/BOND.png")
BUTTON_CROSS = load_template("./template/ui/assets/BUTTON_CROSS.png", rect=(1190, 0, 1280, 70))
CHAT = load_template("./template/ui/assets/CHAT.png")
EXIT = load_template("./template/ui/assets/EXIT.png")
F1 = load_template("./template/ui/assets/F1.png")
F2 = load_template("./template/ui/assets/F2.png")
F3 = load_template("./template/ui/assets/F3.png")
F4 = load_template("./template/ui/assets/F4.png")
F5 = load_template("./template/ui/assets/F5.png")
GET_ITEM = load_template("./template/ui/assets/GET_ITEM.png")
INTERACT = load_template("./template/ui/assets/INTERACT.png", method="avg_color")
MAP = load_template("./template/ui/assets/MAP.png")
MONTH_CARD = load_template("./template/ui/assets/MONTH_CARD.png")
PHONE = load_template("./template/ui/assets/PHONE.png")
SAFE_AREA = load_template("./template/ui/assets/SAFE_AREA.png")
START_1 = load_template("./template/ui/assets/START_1.png")
START_2 = load_template("./template/ui/assets/START_2.png")
START_3 = load_template("./template/ui/assets/START_3.png")