from template.load_template import load_template

BAIT = load_template("./template/fish/assets/BAIT.png", rect=(32, 86, 453, 653))
BUTTON_CHANGE_BAIT = load_template("./template/fish/assets/BUTTON_CHANGE_BAIT.png")
BUTTON_LEFT = load_template("./template/fish/assets/BUTTON_LEFT.png")
BUTTON_MARKET = load_template("./template/fish/assets/BUTTON_MARKET.png")
BUTTON_RIGHT = load_template("./template/fish/assets/BUTTON_RIGHT.png")
BUTTON_SHOP = load_template("./template/fish/assets/BUTTON_SHOP.png")
BUY = load_template("./template/fish/assets/BUY.png")
BUY_CONFIRM = load_template("./template/fish/assets/BUY_CONFIRM.png")
CHANGE_BAIT_CONFIRM = load_template("./template/fish/assets/CHANGE_BAIT_CONFIRM.png")
FISH_BAR_ICON = load_template("./template/fish/assets/FISH_BAR_ICON.png")
FISH_READY = load_template("./template/fish/assets/FISH_READY.png")
FISH_STORAGE = load_template("./template/fish/assets/FISH_STORAGE.png")
FULL_STORAGE = load_template("./template/fish/assets/FULL_STORAGE.png")
HOOK = load_template("./template/fish/assets/HOOK.png")
MARKET = load_template("./template/fish/assets/MARKET.png")
NEED_BAIT = load_template("./template/fish/assets/NEED_BAIT.png")
SELL_ALL = load_template("./template/fish/assets/SELL_ALL.png")
SELL_CONFIRM = load_template("./template/fish/assets/SELL_CONFIRM.png")
SELL_SUCCESS = load_template("./template/fish/assets/SELL_SUCCESS.png")
SHOP_MAX_BUTTON = load_template("./template/fish/assets/SHOP_MAX_BUTTON.png")
START_TO_FISH = load_template("./template/fish/assets/START_TO_FISH.png")