from template.load_template import load_template

CHEST = load_template("./template/combat/assets/CHEST.png", rect=(0, 0, 1280, 720))
CLAIM_DOUBLE = load_template("./template/combat/assets/CLAIM_DOUBLE.png")
CLAIM_SINGLE = load_template("./template/combat/assets/CLAIM_SINGLE.png")
ENTER = load_template("./template/combat/assets/ENTER.png")
EXIT = load_template("./template/combat/assets/EXIT.png")
FOCUS_POINT = load_template("./template/combat/assets/FOCUS_POINT.png", rect=(0, 0, 1280, 720))
SELECTION_1 = load_template("./template/combat/assets/SELECTION_1.png")
SELECTION_2 = load_template("./template/combat/assets/SELECTION_2.png")
SELECTION_3 = load_template("./template/combat/assets/SELECTION_3.png")
SELECTION_4 = load_template("./template/combat/assets/SELECTION_4.png")
SELECTION_5 = load_template("./template/combat/assets/SELECTION_5.png")
SELECTION_6 = load_template("./template/combat/assets/SELECTION_6.png")
SUCCESS = load_template("./template/combat/assets/SUCCESS.png")